server:
  servlet:
    context-path: /atopy-database

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///atopy-database
    username: jp
    password: 1234
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: atopy-database:asia-northeast3:atopy-database
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
